### ISSUE TITLE
`__destruct` should always be allowed

### ISSUE THREAD

**Issue by Ocramius** [InterNations/type-jail#3]
As per today's test runs, I noticed that the `__destruct` method is not allowed to be called on type-jailed objects.

`__destruct` is not actual API, but a language detail, so it should always be allowed to be called.

**Comment by lstrojny** [comment]
Makes sense. Would you also allow it for SuperType jails, even if the supertype doesn’t have a destructor?

**Comment by Ocramius** [comment]
Yeah, it's pretty much private API. Stopping it from executing causes
undefined behaviour.

**Comment by Ocramius** [comment]
I was thinking also about `__sleep`, `__wakeup`, `__get`, `__set`, `__clone` and so on, but couldn't find a use-case so far.

**Comment by lstrojny** [comment]
Thinking about it, my stance would be that `__clone` should be implemented to make sure that the inner `__clone` is called, same for `__wakeup` and `__sleep`.

**Comment by Ocramius** [comment]
@lstrojny `__clone` is an implementation detail (private API). As for `__wakeup` and `__sleep`, I think users should rather rely on `Serializable`

**Comment by Ocramius** [comment]
@lstrojny I will open a new issue for `__clone` if it turns out to be required. For now, #4 should be sufficient to close this off.

**Comment by lstrojny** [comment]
Alright, see my comment in #4
